version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Hello from CircleCI 👋"
      - run: |
          echo "Build report for $(date)" > report.txt
      - store_artifacts:
          path: report.txt
          destination: demo-report

workflows:
  demo:
    jobs:
      - build
