version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "✅ Build step complete"
      - run: |
          echo "Build report for $(date)" > report.txt
      - store_artifacts:
          path: report.txt
          destination: demo-report

  deploy_stub:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "🚀 Deploying to staging… app=${APP_NAME:-demo-app}"

workflows:
  demo:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy_stub:
          requires:
            - hold
